# SPDX-FileCopyrightText: 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Lint source code

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  lint-source-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Lint shell scripts
      uses: bewuethr/shellcheck-action@v2
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - run: |-
        cargo fmt --manifest-path components/Cargo.toml --all --check
        cargo clippy --manifest-path components/Cargo.toml --workspace --all-features -- -Dwarnings
        cargo test --manifest-path components/Cargo.toml --workspace --all-features
